MasterJ93/ATProtoKit

Sources/ATProtoKit/Networking/SessionManager/ATProtocolConfiguration.swift
Describe in detail what this Pull Request does and why it’s needed. Include anything the reviewers need to be aware of.
This PR changes the handle and app password to have public setters. This is needed to be able to try to sign in again in the event of an unsuccessful login, and pass in a corrected set of handle and app password.
N/A
N/A
N/A
- Name: [Joshua Holme]
- GitHub: [JoshuaHolme]
- Bluesky: [josh.holme.social]
=> Remove Private Set From ATProtocolConfiguration

Sources/ATProtoKit/APIReference/ATProtoBlueskyAPI/PostRecord/CreatePostRecord.swift, Sources/ATProtoKit/Utilities/ATProtoTools.swift
My spelunking of the code revealed that the `fetchRecordForURI()` method expects to have a working `UserSession` instance in order to get a `pdsURL` value. But because the method belongs to a bare utility class, it has no such association. Therefore, all attempts to resolve URIs used to resolve posts for threading will always fail. My solution is pretty naive, and I'm 95% sure y'all will shoot it down. I'm happy to play ball to help you get all the right parts talking to each other.
#32 
- Name: [Aaron Vegh]
- GitHub: [aaronvegh]
- Bluesky: …
=> [Bug Fix] Fix Threading Errors By Passing Session to URI Resolution

Sources/ATProtoKit/Utilities/ATFacetParser.swift
When the user posts text that contains non-ascii characters (süch às 💭), the simple ASCII-based range finders flake right out. The issue I created provides examples of what happened when a German did a post with my app. 😬 
My update updates the hashtag regex to include more-inclusive matchers for unicode letters, and uses String.Index values, which are sensitive to multi-byte strings.
#35 
- Name: Aaron Vegh
- GitHub: aaronvegh
=> Handle unicode strings when parsing hashtags, links, mentions

README.md
I tried to click the Bluesky link to follow you and it linked to `bsky.social` instead of `bsky.app`. Went ahead and switched it.
N/A
N/A
N/A
Not needed.
=> Update link to Bluesky profile

Sources/ATProtoKit/Utilities/ATFacetParser.swift
When users post with a hashtag, ATProtoKit kindly parses the text and creates a facet. The text of the facet includes the "#" character. On Bluesky, the resulting post appears with a single hashtag, but tapping on it reveals a double-hash — in other words, the hashtag includes the "#" character, so it becomes "##hashtag". 
Here's an example with a post done with the current version of ATProtoKit: 
https://bsky.app/profile/croissantageddon.bsky.social/post/3l7gi2g2env2u
This change simply snips off that opening # character during facet parsing, so the tag content doesn't have one. Here's an example post using this PR:
https://bsky.app/profile/croissantageddon.bsky.social/post/3l7jbwgvprt2u
Add any other notes about the Pull …
=> Remove literal # from hashtags during posting

Sources/ATProtoKit/APIReference/ATProtoBlueskyAPI/PostRecord/CreatePostRecord.swift, Sources/ATProtoKit/Models/Lexicons/com.atproto/Identity/ComAtprotoIdentityResolveHandle.swift, Sources/ATProtoKit/Utilities/ATFacetParser.swift
I noticed that calls to `resolveHandle` were failing: it appears the pdsURL was being replaced with an access token JWT. This was preventing my Bsky client from being able to post @-mentions.
In providing this fix, I made two changes:
1. I set the pdsURL to the session's `pdsURL` rather than the access token. This must've been an error made earlier.
2. I also noted that the response JSON from the AT protocol endpoint returns a `did` property, not a `handleDID`. Changing that got it all flowing right again.
#45 
- Name: [Replace this with your first and …
=> Ensure mention lookups work

Package.swift
This widens the version of Swift Syntax that ATProtoKit can point to.
This is important as if someone using ATProtoKit depends on a library that uses a later version of Swift Syntax, e.g. 510.0.0, 600.0.0, etc. then the dependencies cannot resolve. Even though the code uses the `from` version of the `package` static method, Apple have used major version semantic versioning bumps for new minor versions of Swift (and for major versions).
Pointing to a wider range of Swift Syntax versions resolves this problem, and allows for wider Swift Syntax version resolution.
Following guidance from Point-Free: https://www.pointfree.co/blog/posts/116-being-a-good-citizen-in-the-land-of-swiftsyntax
If you want to be credited in the CONTRIBUTORS file, you can fill out the form below. Please don't remove …
=> Widens the Swift Syntax version

Sources/ATProtoKit/APIReference/AppBskyAPI/GetPopularFeedGenerators.swift
Forward the session authorization for `getPopularFeedGenerators`
Link any related issues here. Format: `#[issue number]`
Forward the session authorization for `getPopularFeedGenerators` as it's required, for now we get the error 
`unauthorized(error: ATProtoKit.ATHTTPResponseError(error: "AuthMissing", message: "Authentication Required"), wwwAuthenticate: nil)`
- Name: Thomas Ricouard
- GitHub: https://github.com/Dimillian
- Bluesky: https://bsky.app/profile/dimillian.app
=> Forward the session authorization for getPopularFeedGenerators

Sources/ATProtoKit/Models/Lexicons/app.bsky/Graph/AppBskyGraphDefs.swift, Sources/ATProtoKit/Models/Lexicons/app.bsky/Labeler/AppBskyLabelerDefs.swift
This pull request attempts to fix the issues encountered in #55 by implementing a type variable and the corresponding CodingKey enum and then decoding for the type variable, and comparing the decoded variable with the correct type variable to see if we should continue decoding, or if we should throw an error that we are decoding the wrong type.
#55 
This is a pull request to attempt to fix one of the issues I've encountered in #55 after some discussions with the owner of the repo as well as digging into the codebase itself. 
- Name: Andy Lin
- GitHub: @andylin2004
- Bluesky: [Replace with your Bluesky handle if you have one]
=> Potential fix to the embed records not decoding correctly

Sources/ATProtoKit/Utilities/APIClientService.swift
Sets a default user agent that identifies network requests from this SPM
We could add a method for users to update with their own custom user agent down the line, but they can update the ['User-Agent'] header currently if they so desire.
- Name: [Adam Rowe]
- GitHub: [airowe]
- Bluesky: [airowe@bsky.social]
- Email: [adaminsley@gmail.com]
=> Set default user agent

Sources/ATProtoKit/Models/Lexicons/app.bsky/Actor/AppBskyActorDefs.swift
As mentioned in #68 in `ProfileViewDetailedDefinition` the `createdAt` property is missing.
This PR addresses this and is adding the property to the struct.
#68
- Name: [Michael Freiwald]
- GitHub: [mfreiwald]
- Bluesky: [freiwald.dev]
- Email: [michael@freiwald.dev]
=> Add createdAt to ProfileViewDetailedDefinition

Sources/ATProtoKit/Utilities/APIClientService.swift
The `ratelimit-reset` header has a timestamp as its value. 
However, in the `tooManyRequests` 429 error, it is cast to a `TimeInterval` (Double), but header values are (always) Strings.
So it needs to be something like this:
```swift
TimeInterval(headers["ratelimit-reset"] as? String ?? "")
```
This is an example output of the ratelimit headers:
```
ratelimit-limit: 3000
ratelimit-policy: 3000;w=300
ratelimit-remaining: 0
ratelimit-reset: 1734295297
```
=> Fix type of `ratelimit-reset` header

Sources/ATProtoKit/APIReference/ATProtoBlueskyAPI/PostRecord/CreatePostRecord.swift
This updates the `createPostRecord` function to derive only language codes from Locales; previously it was deriving a full region-language code combo, which is incompatible with Bluesky's API.
#82 
- Name: [Replace this with your first and last name or an alias]
- GitHub: [Replace with your GitHub username]
- Bluesky: [Replace with your Bluesky handle if you have one]
- Email: [Replace with your email address, or delete this line]
=> Derive only the language code from the Locale objects

Sources/ATProtoKit/APIReference/AppBskyAPI/ListNotifications.swift
listNotifications only had a `reason` parameter, but the JSON schema requires an array of reasons
https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/notification/listNotifications.json
=> Add Reasons-Array to listNotifications parameter

Sources/ATProtoKit/APIReference/ATProtoBlueskyAPI/PostRecord/CreatePostRecord.swift, Sources/ATProtoKit/Models/Lexicons/app.bsky/Embed/AppBskyEmbedVideo.swift
A string like "en" doesn't decode to Swift `Locale` out-of-the-box.
That's why I changed the language property of the Video#Caption to `String`.
I'm not sure if there are other Models with Locale instead of a plain String for language properties.
See this small example:
```swift
import Foundation
struct Caption: Codable {
let lang: Locale
}
let json = "{\"lang\": \"en\"}"
let data = json.data(using: .utf8)!
do {
let caption = try JSONDecoder().decode(Caption.self, from: data)
} catch {
print(error)
/*
typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "lang", intValue: nil)], debugDescription: "Expected to decode Dictionary<String, Any> but found a string instead.", underlyingError: nil))
*/
}
```
Link any related issues …
=> Change language property from Locale to String for decoding

Sources/ATProtoKit/Models/Lexicons/app.bsky/Video/AppBskyVideoDefs.swift
This adds the last missing job state for video uploads: "JOB_STATE_SCANNED"
#97 
- Name: [Replace this with your first and last name or an alias]
- GitHub: [Replace with your GitHub username]
- Bluesky: [Replace with your Bluesky handle if you have one]
- Email: [Replace with your email address, or delete this line]
=> Defeat the final boss in job states

Sources/ATProtoKit/Models/Lexicons/app.bsky/Graph/AppBskyGraphDefs.swift
Decoding of `ProfileViewDetailedDefinition` with `joinedViaStarterPack` still fails as mentioned in https://github.com/MasterJ93/ATProtoKit/issues/109
I removed the type property in `StarterPackViewBasicDefinition` because it is not part of the official JSON schema.
#109 
See the last comment in the Issue
=> Remove `type` from StarterPackViewBasicDefinition

Sources/ATProtoKit/APIReference/SessionManager/ATProtocolConfiguration.swift
I was doing some work on my auth implementation in Croissant, and I came across something that's either a bug (which this PR fixes) or I'm holding it wrong. I honestly think it could break either way. 😬 
I'm now saving the session's accessToken and refreshToken in the keychain, and instead of authenticating, I'm using the refreshSession call. However, I noticed that the resulting session had a nil value for pdsURL. This obviously prevents any subsequent framework calls from working. 
My fix is a one-liner in the refreshToken call to fallback on the config object's pdsURL value if the session doesn't have it, before setting it to nil. This should have no effect on callers who are "holding it right".
Add any other notes about the …
=> Fallback for refreshSession’s pdsURL

Sources/ATProtoKit/APIReference/ATProtoBlueskyAPI/PostRecord/CreatePostRecord.swift
My Bluesky posting client estimates character count by converting hyperlinks to their final maximum character counts. Bluesky removes the scheme from the URL and truncates to 32 chars. However, in `createPostRecord()`, the post text is clipped to 300 characters before the facet parsing occurs. In the event of a post that, say, ends with a URL, that can get clipped before it gets parsed. Here's an example of a post created by one of my customers, where the final link is truncated in the post text:
https://bsky.app/profile/adfc-gd.bsky.social/post/3lkfygf5afd2a
To remedy, I have swapped the order of operations: first the post text is parsed, making sure facets are generated for the post. Then the text is truncated. Here's that same post under this new method: …
=> Parse for links, *then* clip the post text

Sources/ATProtoKit/APIReference/ATProtoBlueskyAPI/PostRecord/CreatePostRecord.swift, Sources/ATProtoKit/Utilities/ATFacetParser.swift
Bluesky truncates URLs within posts using this simple algorithm: 
* Nip off the scheme "http://" or "https://"
* Clamp the length of the URL text to 32 characters
My posting client, Croissant, respects this logic when calculating the post length as users type their posts in the composer. However, during posting in ATProtoKit, the post text will be truncated to 300 characters, based on the full length of the URLs within. Here's an example post from Croissant that a user complained about:
https://bsky.app/profile/filippo.abyssdomain.expert/post/3lmhaj5zma32u
This post has two URLs, and the second is clipped considerably because while the length of the resolved text was fine, it got clipped because the first URL is counting towards the total.
This PR does a fair bit of wrangling with the …
=> Handle URL truncation in posts to achieve accurate length

Sources/ATProtoKit/Models/Lexicons/com.atproto/Sync/ComAtprotoSyncListRepos.swift, Sources/ATProtoKit/Models/Lexicons/com.atproto/Sync/ComAtprotoSyncListReposByCollection.swift
A quick fix for the `com.atproto.sync.listRepos` and `com.atproto.sync.listReposByCollection` responses.
N/A
N/A
No docs changes here
=> Fix ListRepositoriesOutput and ListRepositoriesByCollectionOutput incorrect CodingKeys

Sources/ATProtoKit/APIReference/AppBskyAPI/MuteActor.swift, Sources/ATProtoKit/APIReference/AppBskyAPI/UnmuteActor.swift
Mute and Unmute requests need to have `application/json` for `ContentType`.
Requests are failing because of wrong `contentTypeValue` in request.
=> Mute and Unmute need to have application/json contentType

Sources/ATProtoKit/Models/Lexicons/app.bsky/Actor/AppBskyActorStatus.swift
StatusRecord should use "app.bsky.embed.external" for embedUntion externalView and not "app.bsky.embed.external#view"
https://github.com/MasterJ93/ATProtoKit/issues/158
=> Use app.bsky.embed.external for StatusRecord (not #view version)

Sources/ATProtoKit/APIReference/AppBskyAPI/AppBskyFeedGetTimelineMethod.swift, Sources/ATProtoKit/APIReference/SessionManager/SessionConfiguration.swift, Sources/ATProtoKit/ATProtoKit.swift
- Add ensureValidToken() method to SessionConfiguration protocol
- Update prepareAuthorizationValue() to refresh tokens for auth-optional methods
- Modify getTimeline() as proof-of-concept for auth-required methods
- Tokens are refreshed if they expire within 10 seconds
- No breaking changes, maintains backward compatibility
This PR implements automatic token refresh functionality to prevent `ExpiredToken` errors when making API calls. The implementation follows the approach discussed in issue #203 and uses a helper method pattern to minimize code changes while maintaining backward compatibility.
- Access tokens expire after ~2 hours, causing API calls to fail with `ExpiredToken` errors
- Users currently must catch these errors and manually refresh tokens
- This creates poor developer …
=> feat: Add automatic token refresh for API methods

Sources/ATProtoKit/APIReference/SessionManager/SessionConfiguration.swift
This PR fixes a gap in SessionConfiguration’s 2FA detection logic.
Previously, 2FA requirements were only detected via .badRequest (HTTP 400) responses containing AuthFactorTokenRequired. Some servers return the same requirement as .unauthorized (HTTP 401). This change adds handling for that case, ensuring the 2FA flow continues correctly regardless of status code.
The update also includes corresponding inline documentation clarifying that both response types are supported.
N/A
- Name: [Rayan Waked]
- GitHub: [rayanwaked]
- Bluesky: [skyliner.app]
- Email: [rayan@waked.dev]
=> Fix 2FA detection to handle both 400 and 401 AuthFactorTokenRequired responses

Sources/ATProtoKit/APIReference/ComAtprotoAPI/ComAtprotoIdentitySignPlcOperationMethod.swift, Sources/ATProtoKit/APIReference/ComAtprotoAPI/ComAtprotoIdentitySubmitPlcOperationMethod.swift, Sources/ATProtoKit/Models/Lexicons/app.bsky/Actor/AppBskyActorDefs.swift, Sources/ATProtoKit/Models/Lexicons/com.atproto/Identity/ComAtprotoIdentitySignPLCOperation.swift, Sources/ATProtoKit/Models/Lexicons/com.atproto/Identity/ComAtprotoIdentitySubmitPLCOperation.swift
Fixed 2 lexicon issues:
1. Preferences `activeProgressGuide` property
2. PLC Operation lexicons and api where incomplete for performing an update to the PLC Directory. These changes align the lexicons and api with the specifications. Includes  proper comments, public init, decode, encode methods too.
Performing a PLC Operation update was not possible due to incorrect lexicons and api signatures.
- Name: Scott Handley
- GitHub: mcprostar205
- Bluesky: h2oskier.bsky.social
=> Fixed lexicons (activeProgressGuide & PLC Operation) and api methods per specifications

Sources/ATProtoKit/Models/Lexicons/app.bsky/Actor/AppBskyActorPutPreferences.swift, Sources/ATProtoKit/Models/Lexicons/com.atproto/Repo/ComAtprotoRepoCreateRecord.swift, Sources/ATProtoKit/Models/Lexicons/com.atproto/Repo/ComAtprotoRepoDeleteRecord.swift, Sources/ATProtoKit/Models/Lexicons/com.atproto/Server/ComAtprotoServerCreateSession.swift
ComAtprotoRepoCreateRecord
PreferenceUnion
CreateSessionRequestBody
DeleteRecordRequestBody
Unable to create instances of lexicons that are missing public initializers. 
Link any related issues here. Format: `#[issue number]`
- [X ] Bug Fix
- [X ] My code follows the [ATProtoKit API Design Guidelines](https://github.com/MasterJ93/ATProtoKit/blob/main/API_GUIDELINES.md) as well as the [Swift API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/).
- [X ] I have performed a self-review of my own code and commented it, particularly in hard-to-understand areas.
- [X ] My changes generate no new warnings or errors in the compiler or runtime.
- [X ] My code is able to build and run on my machine.
Add any …
=> Added more missing public initializers

Sources/ATProtoKit/APIReference/AppBskyAPI/AppBskyNotificationRegisterPushMethod.swift, Sources/ATProtoKit/APIReference/AppBskyAPI/AppBskyNotificationUnregisterPushMethod.swift
Fixes Content-Type header for `registerPush` and `unregisterPush` endpoints to resolve "Wrong request encoding" errors.
- Set `contentTypeValue: "application/json"` (was `nil`) in `AppBskyNotificationRegisterPushMethod.swift`
- Set `contentTypeValue: "application/json"` (was `nil`) in `AppBskyNotificationUnregisterPushMethod.swift`
The `registerPush` and `unregisterPush` methods were passing `contentTypeValue: nil` to `createRequest()`, which caused the `Content-Type` header to not be set. While the request body was correctly JSON-encoded via `toJsonData()`, the missing header caused PDS to reject requests with a 400 "Wrong request encoding" error.
Explicitly set `contentTypeValue` to `"application/json"` to ensure the correct Content-Type header is sent with the request.
- Push …
=> Fix registerPush and unregisterPush Content-Type header
